# Generated by Django 5.1.6 on 2025-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
