# Generated by Django 5.1.6 on 2025-02-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_qrcode', '0002_remove_qrcode_assigned_to_qrcode_is_registered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
