# Generated by Django 5.1.6 on 2025-02-27 13:52

import django.db.models.deletion
import tree_planting.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make_qrcode', '0003_qrcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to=tree_planting.utils.upload_image_path, verbose_name='تصویر درخت')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='make_qrcode.qrcode', verbose_name='انتخاب درخت')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
    ]
