# Generated by Django 5.1.6 on 2025-02-27 14:42

import ckeditor_uploader.fields
import django.db.models.deletion
import tree_planting.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته بندی')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مطلب')),
                ('image', models.ImageField(upload_to=tree_planting.utils.upload_image_path, verbose_name='بنر خبر -300*360-')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پست')),
                ('description', models.TextField(max_length=690, verbose_name='توضیحات کوتاه(یک پاراگراف)')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن خبر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.category')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
