# Generated by Django 5.1.6 on 2025-03-19 11:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن خبر'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('reply_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ ادمین')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='بلاگ مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
